In [2]:
import requests
import bs4
from bs4 import BeautifulSoup
import numpy as np
import pandas as pd
from tqdm import tqdm
from random import randint
from time import sleep

In [3]:
df = pd.read_csv('AU_jobs.csv')

In [6]:
df = df.drop(columns='Unnamed: 0')

In [7]:
df = df.drop_duplicates().dropna().reset_index(drop=True)

In [8]:
df

,job_title,company_name,company_location,salary,job_snippet
0,newEcologist/Data Scientist,Department of Agriculture & Water Resources,Darwin NT,"$110,092 - $118,412 a year",Experience developing AI/deep learning workflo...
1,newEcologist/Data Scientist,Australian Department of the Environment,Darwin NT,"$110,092 - $118,412 a year",Experience developing AI/deep learning workflo...
2,newData Scientist,The Staffing Group,Sydney NSW+1 location,"$80,000 - $150,000 a year","A strong background in data science, analytics..."
3,newData Professional - Data Analyst/Scientist ...,The Staffing Group,Melbourne VIC+1 location,"$70,000 - $120,000 a year",We are looking for a data analyst/scientist wh...
4,Junior Machine Learning Engineer,XY Sense,Melbourne VIC,"$70,000 - $90,000 a year",Reporting directly to the CTO with technical l...
5,newData Scientists,Curtin University of Technology,Perth WA,"$92,457 - $99,271 a year","Understanding of data science, computational m..."
6,"Senior Data Scientist, ESG Innovation and Anal...",S&P Global,Sydney NSW,"$82,600 - $230,200 a year",Demonstrated skills in data and project manage...
7,Data Scientist,Ignite Specialist Recruitment Services,Australia,$110 - $150 an hour,Currently looking for a strong data scientist ...
8,Senior Data Scientist,Curtin University of Technology,Perth WA,"$103,813 a year","Understanding of data science, computational m..."
9,Lecturer Data Science,University of Newcastle,Sydney NSW,"$103,221 - $122,576 a year",The vision of the school is aligned with the U...
10,"Scientist, Applied Bushfire Science","NSW Government -Environment, Energy and Science",Sydney NSW,"$95,516 a year",Further development of the Threatened Species ...
11,Data Scientist,Technology Recruiting Solutions,Melbourne VIC,"$145,000 - $160,000 a year",Proven experience in a data or statistical ana...
12,Customer Insights & Data Analyst,Australian College of Nursing,Sydney NSW,"$100,000 - $110,000 a year",Experience with Higher Education and student e...
13,CSIRO Postdoctoral Fellowship - Edge Machine L...,CSIRO,Brisbane QLD,"$88,000 - $96,000 a year",CSIRO Early Research Career (CERC) Postdoctora...
14,newPrincipal Statistician,Australian Bureau of Meteorology,Melbourne VIC+1 location,"$141,591 - $184,308 a year",The Principal Statistician will bolster the Bu...
15,Research Fellow in Statistical Data Science,University of Wollongong,New South Wales,"$104,870 - $127,382 a year","Fixed Term, full-time appointment (3 years, co..."
16,Data Scientist,Morgan McKinley,Sydney Central Business District NSW,"$160,000 - $180,000 a year",Work within a forward thinking team to extract...
17,newAssociate Data Scientist,The Staffing Group,Sydney NSW,"$60,000 - $80,000 a year","A strong interest in data science, analytics, ..."
18,Research Fellow – Machine Learning and Compute...,Monash University,Clayton VIC,"$101,130 - $120,093 a year",Experience with data augmentation and simulati...
19,Data Scientist Team Lead,Clicks IT Recruitment,Brisbane Central Business District QLD,"$140,000 - $150,000 a year",Develop and deliver data solutions through the...
20,LECTURER / SENIOR LECTURER IN STATISTICS (DATA...,University of Melbourne,Parkville VIC,"$107,547 - $127,707 a year",The successful applicant is expected to develo...
21,Senior Data Scientist,Firesoft People,Sydney NSW•Remote,"$140,000 - $160,000 a year",Experience in leading and mentoring teams of d...
22,Senior Data Engineer,State Library of Victoria,Melbourne City Centre VIC+1 location•Remote,"$113,412 - $124,183 a year","Experience in data wrangling, data development..."
23,newSenior Data Scientists,The Staffing Group,Perth WA,"$80,000 - $150,000 a year","Understanding of data science, computational m..."
24,newTeam Lead - Software and Data Science,The Staffing Group,Brisbane QLD•Remote,"$80,000 - $150,000 a year","Develop, test and deploy improvements to machi..."
25,Analytics Translator,Technology Recruiting Solutions,Melbourne VIC,"$190,000 - $200,000 a year",Have a financial or mathematical background bu...
26,Lecturer – Data Science (CIT),University of Newcastle,Sydney NSW,"$103,221 - $122,576 a year",The vision of the school is aligned with the U...
27,Data Science Manager,Talent International,Australia,"$170,000 - $185,000 a year",Work with analytics partners to provision data...
28,Advanced Analytics Manager – Data Science,Technology Recruiting Solutions,Melbourne VIC,"$180,000 - $200,000 a year",This position will also provide technical expe...
29,Team Leader - Data Reporting & Analytics,Michael Page,Brisbane Central Business District QLD,"$120,000 - $170,000 a year",Experience working in a federated data environ...
30,Principal Statistician,Bureau of Meteorology Brisbane,Brisbane QLD,"$141,591 - $184,307 a year",The Principal Statistician will bolster the Bu...
31,newCSIRO Postdoctoral Fellowship in NLP and Kn...,CSIRO,Sydney NSW,"$89,000 - $98,000 a year",Demonstrated experience in working with real-w...
32,Head of Data Analytics – Platforms & Architecture,FutureYou,Sydney NSW,"$200,000 a year",Practical experience in BI/Data/Analytics incl...
33,Data Scientist,Digital Alchemy,Sydney NSW,"$90,000 - $120,000 a year",Manage data quality in budget request sandbox....
34,Data Scientist,Catch.com.au,Bentleigh East VIC•Temporarily Remote,"$110,000 - $145,000 a year",Catch is embarking on a journey of data-driven...
35,Data Scientist,TROOCOO Pty Ltd,Sydney NSW,"$140,000 a year",Good understanding of data engineering princip...
36,Machine Learning Engineer,mPort Ltd,Crows Nest NSW•Temporarily Remote,"$110,000 - $130,000 a year",Devise and carry out relevant experiments to v...
37,newMachine Learning Engineer,Language Confidence,Sydney NSW•Remote,"$100,000 a year",Our vision is a full suite of AI tools for Aut...
38,Data Scientist (remote),Virtually Human Studio,Remote,"$40,000 - $80,000 a year","You will have experience with data algorithms,..."
39,QA Engineer - Data Analytics,Yellowfin Pvt Ltd,Melbourne VIC•Temporarily Remote,"$75,000 - $80,000 a year",Proficient experience with database administra...
40,Data Scientist / Engineer,Liftango,Temporarily Remote,"$110,000 a year",Conducting research on different towns/cities/...
41,Senior Data Scientist - Fraud Analytics (Insur...,Talent Insights Group,Sydney NSW,"$140,000 a year",In depth knowledge on data visualisation - Pow...
42,newSenior Analyst - Data Science - Retail Bank,Bluefin Resources,Sydney NSW,"$135,000 - $145,000 a year",Experience in handling high volume databases p...
43,Senior Data Scientist,BizPay,Sydney NSW,"$130,000 - $160,000 a year","Research, design and implement ML/DL models to..."
44,Senior Machine Learning Engineer,Maiden Ventures Co Pty Ltd,Naremburn NSW•Remote,"$180,000 - $200,000 a year",Knowledge and experience of data science and A...
45,"Team Lead, Machine Learning Operations",Zendesk,Melbourne VIC•Remote,"$175,000 a year",Familiarity with data engineering tools.\nOur ...
46,Data Science Engineer,Sustainability Consulting,Sydney NSW,"$130,000 - $150,000 a year","Ensuring data quality, extraction and cleansin..."
47,Data Analyst - Advanced Analytics Team,Talent Insights Group,Melbourne VIC,"$100,000 - $120,000 a year",Advanced Analytics team - consult across diffe...
48,Lead Software Engineer (Machine Learning),Whispir,Melbourne VIC,"$60,000 - $70,000 a year",Excellent understanding of & experience (to va...
49,Mid-Level Machine Learning Engineer,Talent Insights Group,Sydney NSW•Remote,"$130,000 - $140,000 a year",You may be coming from either a data science o...
50,Data Scientist,Zone IT Solutions,Sydney NSW,"$80,000 - $180,000 a year",Core exp as a Data Scientist – developing and ...
51,Data Science Manager,Troy Recruitment Pty Ltd,Sydney NSW,"$170,000 - $190,000 a year","Manage, create and provide data analytic solut..."
52,Actuarial and Data Science Manager,Troy Recruitment Pty Ltd,Sydney NSW+1 location,"$170,000 - $190,000 a year",Some experience with data analytics and the de...
53,"Data and Analytics Consulting Partner, Sydney ...",inDmand,Melbourne VIC,"$200,000 - $250,000 a year",High profile role - Influence how this practic...
54,Machine Learning Engineer,BizPay,Sydney NSW,"$130,000 - $160,000 a year","Design, build, test, and deploy scalable ML pi..."
55,Machine Learning Solutions Architect,Certus Recruitment Group,Melbourne VIC•Temporarily Remote,"$150,000 - $200,000 a year","Our client, a fast-growing technology-focused ..."
56,Senior Machine Learning Engineer,Rokt,Sydney NSW,"$150,000 - $180,000 a year","Strong understanding in software engineering ,..."
57,"Analytics Consulting Partner, Sydney CBD",inDmand,Sydney NSW,"$200,000 - $250,000 a year",High profile role - Influence how this practic...
58,Analytics Consultant - Fraud - APAC,Eagna Consulting,Sydney NSW,"$230,000 a year",Build analytical data models and present resul...
59,Senior Machine Learning Engineer - Marketing T...,Talent Insights Group,Sydney NSW,"$160,000 - $180,000 a year",You will also help deploy and productionise ma...

In [12]:
df = df[~df.salary.str.contains("week","month")]

In [13]:
df = df[~df.salary.str.contains("hour")]

In [14]:
yearly_salary = df.reset_index(drop=True)

In [15]:
def strip_salary(x):
    nums = []
    y = x.replace('$','').replace(',','')
    for i in y.split():
        if i.isnumeric():
            nums.append(int(i))
    if len(nums) == 2:
        return 0.5*(nums[0]+nums[1])
    else:
        return nums[0]

In [16]:
yearly_salary['salary'] = yearly_salary.salary.map(strip_salary)

In [19]:
def convert_aud_to_gbp(amount):
    return amount*0.55

In [21]:
yearly_salary['salary'] = yearly_salary.salary.map(convert_aud_to_gbp)

In [22]:
yearly_salary

,job_title,company_name,company_location,salary,job_snippet
0,newEcologist/Data Scientist,Department of Agriculture & Water Resources,Darwin NT,62838.600,Experience developing AI/deep learning workflo...
1,newEcologist/Data Scientist,Australian Department of the Environment,Darwin NT,62838.600,Experience developing AI/deep learning workflo...
2,newData Scientist,The Staffing Group,Sydney NSW+1 location,63250.000,"A strong background in data science, analytics..."
3,newData Professional - Data Analyst/Scientist ...,The Staffing Group,Melbourne VIC+1 location,52250.000,We are looking for a data analyst/scientist wh...
4,Junior Machine Learning Engineer,XY Sense,Melbourne VIC,44000.000,Reporting directly to the CTO with technical l...
5,newData Scientists,Curtin University of Technology,Perth WA,52725.200,"Understanding of data science, computational m..."
6,"Senior Data Scientist, ESG Innovation and Anal...",S&P Global,Sydney NSW,86020.000,Demonstrated skills in data and project manage...
7,Senior Data Scientist,Curtin University of Technology,Perth WA,57097.150,"Understanding of data science, computational m..."
8,Lecturer Data Science,University of Newcastle,Sydney NSW,62094.175,The vision of the school is aligned with the U...
9,"Scientist, Applied Bushfire Science","NSW Government -Environment, Energy and Science",Sydney NSW,52533.800,Further development of the Threatened Species ...
10,Data Scientist,Technology Recruiting Solutions,Melbourne VIC,83875.000,Proven experience in a data or statistical ana...
11,Customer Insights & Data Analyst,Australian College of Nursing,Sydney NSW,57750.000,Experience with Higher Education and student e...
12,CSIRO Postdoctoral Fellowship - Edge Machine L...,CSIRO,Brisbane QLD,50600.000,CSIRO Early Research Career (CERC) Postdoctora...
13,newPrincipal Statistician,Australian Bureau of Meteorology,Melbourne VIC+1 location,89622.225,The Principal Statistician will bolster the Bu...
14,Research Fellow in Statistical Data Science,University of Wollongong,New South Wales,63869.300,"Fixed Term, full-time appointment (3 years, co..."
15,Data Scientist,Morgan McKinley,Sydney Central Business District NSW,93500.000,Work within a forward thinking team to extract...
16,newAssociate Data Scientist,The Staffing Group,Sydney NSW,38500.000,"A strong interest in data science, analytics, ..."
17,Research Fellow – Machine Learning and Compute...,Monash University,Clayton VIC,60836.325,Experience with data augmentation and simulati...
18,Data Scientist Team Lead,Clicks IT Recruitment,Brisbane Central Business District QLD,79750.000,Develop and deliver data solutions through the...
19,LECTURER / SENIOR LECTURER IN STATISTICS (DATA...,University of Melbourne,Parkville VIC,64694.850,The successful applicant is expected to develo...
20,Senior Data Scientist,Firesoft People,Sydney NSW•Remote,82500.000,Experience in leading and mentoring teams of d...
21,Senior Data Engineer,State Library of Victoria,Melbourne City Centre VIC+1 location•Remote,65338.625,"Experience in data wrangling, data development..."
22,newSenior Data Scientists,The Staffing Group,Perth WA,63250.000,"Understanding of data science, computational m..."
23,newTeam Lead - Software and Data Science,The Staffing Group,Brisbane QLD•Remote,63250.000,"Develop, test and deploy improvements to machi..."
24,Analytics Translator,Technology Recruiting Solutions,Melbourne VIC,107250.000,Have a financial or mathematical background bu...
25,Lecturer – Data Science (CIT),University of Newcastle,Sydney NSW,62094.175,The vision of the school is aligned with the U...
26,Data Science Manager,Talent International,Australia,97625.000,Work with analytics partners to provision data...
27,Advanced Analytics Manager – Data Science,Technology Recruiting Solutions,Melbourne VIC,104500.000,This position will also provide technical expe...
28,Team Leader - Data Reporting & Analytics,Michael Page,Brisbane Central Business District QLD,79750.000,Experience working in a federated data environ...
29,Principal Statistician,Bureau of Meteorology Brisbane,Brisbane QLD,89621.950,The Principal Statistician will bolster the Bu...
30,newCSIRO Postdoctoral Fellowship in NLP and Kn...,CSIRO,Sydney NSW,51425.000,Demonstrated experience in working with real-w...
31,Head of Data Analytics – Platforms & Architecture,FutureYou,Sydney NSW,110000.000,Practical experience in BI/Data/Analytics incl...
32,Data Scientist,Digital Alchemy,Sydney NSW,57750.000,Manage data quality in budget request sandbox....
33,Data Scientist,Catch.com.au,Bentleigh East VIC•Temporarily Remote,70125.000,Catch is embarking on a journey of data-driven...
34,Data Scientist,TROOCOO Pty Ltd,Sydney NSW,77000.000,Good understanding of data engineering princip...
35,Machine Learning Engineer,mPort Ltd,Crows Nest NSW•Temporarily Remote,66000.000,Devise and carry out relevant experiments to v...
36,newMachine Learning Engineer,Language Confidence,Sydney NSW•Remote,55000.000,Our vision is a full suite of AI tools for Aut...
37,Data Scientist (remote),Virtually Human Studio,Remote,33000.000,"You will have experience with data algorithms,..."
38,QA Engineer - Data Analytics,Yellowfin Pvt Ltd,Melbourne VIC•Temporarily Remote,42625.000,Proficient experience with database administra...
39,Data Scientist / Engineer,Liftango,Temporarily Remote,60500.000,Conducting research on different towns/cities/...
40,Senior Data Scientist - Fraud Analytics (Insur...,Talent Insights Group,Sydney NSW,77000.000,In depth knowledge on data visualisation - Pow...
41,newSenior Analyst - Data Science - Retail Bank,Bluefin Resources,Sydney NSW,77000.000,Experience in handling high volume databases p...
42,Senior Data Scientist,BizPay,Sydney NSW,79750.000,"Research, design and implement ML/DL models to..."
43,Senior Machine Learning Engineer,Maiden Ventures Co Pty Ltd,Naremburn NSW•Remote,104500.000,Knowledge and experience of data science and A...
44,"Team Lead, Machine Learning Operations",Zendesk,Melbourne VIC•Remote,96250.000,Familiarity with data engineering tools.\nOur ...
45,Data Science Engineer,Sustainability Consulting,Sydney NSW,77000.000,"Ensuring data quality, extraction and cleansin..."
46,Data Analyst - Advanced Analytics Team,Talent Insights Group,Melbourne VIC,60500.000,Advanced Analytics team - consult across diffe...
47,Lead Software Engineer (Machine Learning),Whispir,Melbourne VIC,35750.000,Excellent understanding of & experience (to va...
48,Mid-Level Machine Learning Engineer,Talent Insights Group,Sydney NSW•Remote,74250.000,You may be coming from either a data science o...
49,Data Scientist,Zone IT Solutions,Sydney NSW,71500.000,Core exp as a Data Scientist – developing and ...
50,Data Science Manager,Troy Recruitment Pty Ltd,Sydney NSW,99000.000,"Manage, create and provide data analytic solut..."
51,Actuarial and Data Science Manager,Troy Recruitment Pty Ltd,Sydney NSW+1 location,99000.000,Some experience with data analytics and the de...
52,"Data and Analytics Consulting Partner, Sydney ...",inDmand,Melbourne VIC,123750.000,High profile role - Influence how this practic...
53,Machine Learning Engineer,BizPay,Sydney NSW,79750.000,"Design, build, test, and deploy scalable ML pi..."
54,Machine Learning Solutions Architect,Certus Recruitment Group,Melbourne VIC•Temporarily Remote,96250.000,"Our client, a fast-growing technology-focused ..."
55,Senior Machine Learning Engineer,Rokt,Sydney NSW,90750.000,"Strong understanding in software engineering ,..."
56,"Analytics Consulting Partner, Sydney CBD",inDmand,Sydney NSW,123750.000,High profile role - Influence how this practic...
57,Analytics Consultant - Fraud - APAC,Eagna Consulting,Sydney NSW,126500.000,Build analytical data models and present resul...
58,Senior Machine Learning Engineer - Marketing T...,Talent Insights Group,Sydney NSW,93500.000,You will also help deploy and productionise ma...

In [27]:
au_df = yearly_salary

In [28]:
au_df

,job_title,company_name,company_location,salary,job_snippet,country_location
0,newEcologist/Data Scientist,Department of Agriculture & Water Resources,Darwin NT,62838.600,Experience developing AI/deep learning workflo...,AU
1,newEcologist/Data Scientist,Australian Department of the Environment,Darwin NT,62838.600,Experience developing AI/deep learning workflo...,AU
2,newData Scientist,The Staffing Group,Sydney NSW+1 location,63250.000,"A strong background in data science, analytics...",AU
3,newData Professional - Data Analyst/Scientist ...,The Staffing Group,Melbourne VIC+1 location,52250.000,We are looking for a data analyst/scientist wh...,AU
4,Junior Machine Learning Engineer,XY Sense,Melbourne VIC,44000.000,Reporting directly to the CTO with technical l...,AU
5,newData Scientists,Curtin University of Technology,Perth WA,52725.200,"Understanding of data science, computational m...",AU
6,"Senior Data Scientist, ESG Innovation and Anal...",S&P Global,Sydney NSW,86020.000,Demonstrated skills in data and project manage...,AU
7,Senior Data Scientist,Curtin University of Technology,Perth WA,57097.150,"Understanding of data science, computational m...",AU
8,Lecturer Data Science,University of Newcastle,Sydney NSW,62094.175,The vision of the school is aligned with the U...,AU
9,"Scientist, Applied Bushfire Science","NSW Government -Environment, Energy and Science",Sydney NSW,52533.800,Further development of the Threatened Species ...,AU
10,Data Scientist,Technology Recruiting Solutions,Melbourne VIC,83875.000,Proven experience in a data or statistical ana...,AU
11,Customer Insights & Data Analyst,Australian College of Nursing,Sydney NSW,57750.000,Experience with Higher Education and student e...,AU
12,CSIRO Postdoctoral Fellowship - Edge Machine L...,CSIRO,Brisbane QLD,50600.000,CSIRO Early Research Career (CERC) Postdoctora...,AU
13,newPrincipal Statistician,Australian Bureau of Meteorology,Melbourne VIC+1 location,89622.225,The Principal Statistician will bolster the Bu...,AU
14,Research Fellow in Statistical Data Science,University of Wollongong,New South Wales,63869.300,"Fixed Term, full-time appointment (3 years, co...",AU
15,Data Scientist,Morgan McKinley,Sydney Central Business District NSW,93500.000,Work within a forward thinking team to extract...,AU
16,newAssociate Data Scientist,The Staffing Group,Sydney NSW,38500.000,"A strong interest in data science, analytics, ...",AU
17,Research Fellow – Machine Learning and Compute...,Monash University,Clayton VIC,60836.325,Experience with data augmentation and simulati...,AU
18,Data Scientist Team Lead,Clicks IT Recruitment,Brisbane Central Business District QLD,79750.000,Develop and deliver data solutions through the...,AU
19,LECTURER / SENIOR LECTURER IN STATISTICS (DATA...,University of Melbourne,Parkville VIC,64694.850,The successful applicant is expected to develo...,AU
20,Senior Data Scientist,Firesoft People,Sydney NSW•Remote,82500.000,Experience in leading and mentoring teams of d...,AU
21,Senior Data Engineer,State Library of Victoria,Melbourne City Centre VIC+1 location•Remote,65338.625,"Experience in data wrangling, data development...",AU
22,newSenior Data Scientists,The Staffing Group,Perth WA,63250.000,"Understanding of data science, computational m...",AU
23,newTeam Lead - Software and Data Science,The Staffing Group,Brisbane QLD•Remote,63250.000,"Develop, test and deploy improvements to machi...",AU
24,Analytics Translator,Technology Recruiting Solutions,Melbourne VIC,107250.000,Have a financial or mathematical background bu...,AU
25,Lecturer – Data Science (CIT),University of Newcastle,Sydney NSW,62094.175,The vision of the school is aligned with the U...,AU
26,Data Science Manager,Talent International,Australia,97625.000,Work with analytics partners to provision data...,AU
27,Advanced Analytics Manager – Data Science,Technology Recruiting Solutions,Melbourne VIC,104500.000,This position will also provide technical expe...,AU
28,Team Leader - Data Reporting & Analytics,Michael Page,Brisbane Central Business District QLD,79750.000,Experience working in a federated data environ...,AU
29,Principal Statistician,Bureau of Meteorology Brisbane,Brisbane QLD,89621.950,The Principal Statistician will bolster the Bu...,AU
30,newCSIRO Postdoctoral Fellowship in NLP and Kn...,CSIRO,Sydney NSW,51425.000,Demonstrated experience in working with real-w...,AU
31,Head of Data Analytics – Platforms & Architecture,FutureYou,Sydney NSW,110000.000,Practical experience in BI/Data/Analytics incl...,AU
32,Data Scientist,Digital Alchemy,Sydney NSW,57750.000,Manage data quality in budget request sandbox....,AU
33,Data Scientist,Catch.com.au,Bentleigh East VIC•Temporarily Remote,70125.000,Catch is embarking on a journey of data-driven...,AU
34,Data Scientist,TROOCOO Pty Ltd,Sydney NSW,77000.000,Good understanding of data engineering princip...,AU
35,Machine Learning Engineer,mPort Ltd,Crows Nest NSW•Temporarily Remote,66000.000,Devise and carry out relevant experiments to v...,AU
36,newMachine Learning Engineer,Language Confidence,Sydney NSW•Remote,55000.000,Our vision is a full suite of AI tools for Aut...,AU
37,Data Scientist (remote),Virtually Human Studio,Remote,33000.000,"You will have experience with data algorithms,...",AU
38,QA Engineer - Data Analytics,Yellowfin Pvt Ltd,Melbourne VIC•Temporarily Remote,42625.000,Proficient experience with database administra...,AU
39,Data Scientist / Engineer,Liftango,Temporarily Remote,60500.000,Conducting research on different towns/cities/...,AU
40,Senior Data Scientist - Fraud Analytics (Insur...,Talent Insights Group,Sydney NSW,77000.000,In depth knowledge on data visualisation - Pow...,AU
41,newSenior Analyst - Data Science - Retail Bank,Bluefin Resources,Sydney NSW,77000.000,Experience in handling high volume databases p...,AU
42,Senior Data Scientist,BizPay,Sydney NSW,79750.000,"Research, design and implement ML/DL models to...",AU
43,Senior Machine Learning Engineer,Maiden Ventures Co Pty Ltd,Naremburn NSW•Remote,104500.000,Knowledge and experience of data science and A...,AU
44,"Team Lead, Machine Learning Operations",Zendesk,Melbourne VIC•Remote,96250.000,Familiarity with data engineering tools.\nOur ...,AU
45,Data Science Engineer,Sustainability Consulting,Sydney NSW,77000.000,"Ensuring data quality, extraction and cleansin...",AU
46,Data Analyst - Advanced Analytics Team,Talent Insights Group,Melbourne VIC,60500.000,Advanced Analytics team - consult across diffe...,AU
47,Lead Software Engineer (Machine Learning),Whispir,Melbourne VIC,35750.000,Excellent understanding of & experience (to va...,AU
48,Mid-Level Machine Learning Engineer,Talent Insights Group,Sydney NSW•Remote,74250.000,You may be coming from either a data science o...,AU
49,Data Scientist,Zone IT Solutions,Sydney NSW,71500.000,Core exp as a Data Scientist – developing and ...,AU
50,Data Science Manager,Troy Recruitment Pty Ltd,Sydney NSW,99000.000,"Manage, create and provide data analytic solut...",AU
51,Actuarial and Data Science Manager,Troy Recruitment Pty Ltd,Sydney NSW+1 location,99000.000,Some experience with data analytics and the de...,AU
52,"Data and Analytics Consulting Partner, Sydney ...",inDmand,Melbourne VIC,123750.000,High profile role - Influence how this practic...,AU
53,Machine Learning Engineer,BizPay,Sydney NSW,79750.000,"Design, build, test, and deploy scalable ML pi...",AU
54,Machine Learning Solutions Architect,Certus Recruitment Group,Melbourne VIC•Temporarily Remote,96250.000,"Our client, a fast-growing technology-focused ...",AU
55,Senior Machine Learning Engineer,Rokt,Sydney NSW,90750.000,"Strong understanding in software engineering ,...",AU
56,"Analytics Consulting Partner, Sydney CBD",inDmand,Sydney NSW,123750.000,High profile role - Influence how this practic...,AU
57,Analytics Consultant - Fraud - APAC,Eagna Consulting,Sydney NSW,126500.000,Build analytical data models and present resul...,AU
58,Senior Machine Learning Engineer - Marketing T...,Talent Insights Group,Sydney NSW,93500.000,You will also help deploy and productionise ma...,AU

In [25]:
au_df['country_location'] = 'AU'

In [26]:
au_df.to_csv('au_df')