In [35]:
import requests
import bs4
from bs4 import BeautifulSoup
import numpy as np
import pandas as pd
from tqdm import tqdm
from random import randint
from time import sleep

In [34]:
def find_job_title(result):
    try: 
        return result.find(class_='jobTitle').text
    except:
        return np.nan

In [29]:
def find_company_name(result):
    try:
        return result.find(class_='companyName').text
    except: 
        return np.nan

In [30]:
def find_company_location(result):
    try:
        return result.find(class_='companyLocation').text
    except: 
        return np.nan

In [31]:
def find_job_snippet(result):
    try:
        return result.find(class_='job-snippet').text.strip('\n')
    except:
        return np.nan

In [32]:
def find_salary(result):
    try:
        return result.find(class_='salary-snippet').text
    except:
        return np.nan

In [18]:
job_title = []
company_name = []
company_location = []
salary = []
snippet = []

In [19]:
for start in tqdm(range(0, 1764, 16)):
        url = "https://ca.indeed.com/jobs?q=data+science&start={}".format(start)
        r = requests.get(url)

        sleep(randint(10,20))
        
        soup = BeautifulSoup(r.text, 'html.parser')
        for i in soup .find_all('div', class_='job_seen_beacon'):
            job_title.append(find_job_title(i))
            company_name.append(find_company_name(i))
            company_location.append(find_company_location(i))
            salary.append(find_salary(i))
            snippet.append(find_job_snippet(i))

100%|██████████| 111/111 [31:13<00:00, 16.88s/it]

In [36]:
CA_jobs = pd.DataFrame(list(zip(job_title, company_name, company_location, salary, snippet)),
               columns =['job_title', 'company_name', 'company_location', 'salary','job_snippet'])

CA_jobs.head()
CA_jobs.count()

NameError: name 'job_title' is not defined

In [27]:
CA_jobs_no_dup = CA_jobs.drop_duplicates(subset=None, keep='first', inplace=False, ignore_index=False)
CA_jobs_no_dup.count()

NameError: name 'CA_jobs' is not defined

In [35]:
CA_jobs_no_dup.to_csv('CA_jobs.csv')

In [39]:
df = pd.read_csv('CA_jobs.csv')

In [40]:
df = df.drop(columns='Unnamed: 0')

In [52]:
df = df.drop_duplicates().dropna().reset_index(drop=True)
df.head(35)

,job_title,company_name,company_location,salary,job_snippet
0,Data Scientist,Genpact,"Montréal, QC•Temporarily Remote","$55,590 - $118,000 a year",Knowledge of best practices in data analysis a...
1,Senior Machine Learning/ Data Scientist at Upw...,Upwork,Remote,"$100,000 - $200,000 a year","Collaborate closely with data scientists, engi..."
2,newData Scientist - Medical Diagnostics Projec...,CorGTA Inc.,"Ottawa, ON•Remote","$85,000 - $95,000 a year","Pay: $85,000 - $95,000 base plus benefits and ..."
3,data scientist,Tiger Analytics Inc.,"Toronto, ON•Remote","$110,000 - $130,000 a year","Research and document data requirements, data ..."
4,data scientist,BluVec Technologies INC,"Burnaby, BC","$70,000 - $120,000 a year","Research and document data requirements, data ..."
5,newData Scientist,Altair Engineering,"Toronto, ON","$59,394 - $141,315 a year",The goal of the data scientist is to provide i...
6,Data/Business Intelligence Analyst (Remote),Mero,"Toronto, ON•Remote","$30,000 - $65,000 a year",You will be closely involved with both the bus...
7,Data Science Instructor,Journey Education,Canada•Remote,"$10,000 - $15,000 a month",As a data science instructor you will be respo...
8,Database / Data Science Developer,AstraNorth,"Montréal, QC•Temporarily Remote","$54,434 a year",Data Science MS or Phd in Computer Science Dat...
9,Data Science Instructor,Juno College of Technology,"Toronto, ON•Remote","$70,000 - $85,000 a year",Are passionate about teaching data science and...
10,Data Scientist,Phyla,"Montréal, QC•Remote","$80,000 - $110,000 a year",Data science and AI: 3 years (required).\nExpe...
11,Join Statistics Canada for Assistant Director ...,Statistics Canada,"Ottawa, ON•Temporarily Remote","$122,991 - $140,571 a year",ASSET10 Experience in the implementation of so...
12,Repost - Statistical Data Analyst,York Region,"East Gwillimbury, ON",$40.60 - $44.12 an hour,Monitors and reviews database information and ...
13,Statistical Program Data Analyst,York Region,"Newmarket, ON",$40.60 - $44.12 an hour,"Reporting to the Supervisor, Data Services, is..."
14,Senior Fleet Data Analyst,BC Transit,"Victoria, BC","$6,715 - $8,063 a month","3+ years of manipulating data sets, building s..."
15,newartificial intelligence (AI) designer,MIR Services,"Concord, ON","$90,000 a year",Collect and document user's requirements and d...
16,Sessional Lecturer - MSC2019H - Information an...,University of Toronto,"Mississauga, ON+1 location","$15,500 a month","Qualifications: Physical sciences, or engineer..."
17,Health Data Analyst,Sioux Lookout First Nations Health Authority,"Sioux Lookout, ON","$78,804 a year",Experience with common data science and data v...
18,newBusiness Intelligence Analyst,Government of Alberta,"Edmonton, AB","$5,228 - $6,857 a month",Formal training in data science;\nCandidates s...
19,mathematician,1226299AlbertaLTD,"Edmonton, AB",$43 an hour,Conduct research into the mathematical basis o...
20,"Data Analyst, Equity, Diversity and Inclusion",Waterloo Regional Police Service,"Cambridge, ON","$89,619 a year",Assist with data integrity and quality control...
21,BAND 2 - IT Data Analyst,BC Public Service,Canada,"$66,900 - $94,600 a year",Minimum 1 year of experience working on data a...
22,Business Intelligence Analyst (FT),Waypoint Centre for Mental Health Care,"Penetanguishene, ON",$38.99 - $46.37 an hour,Demonstrated experience with validating and au...
23,Canada / Stage Data Engineer/Scientist H/F,Neoxia,"Montréal, QC","$45,000 - $55,000 a year","Au sein de la Data Factory de Neoxia, tu pourr..."
24,"Senior Analyst, Advanced Analytics",Canadian Air Transport Security Authority,"Ottawa, ON","$68,475 - $85,649 a year",Graduation from a recognized university with a...
25,newprogrammeur/programmeuse en intelligence ar...,XEOS Imagerie inc.,"Quebec City, QC•Remote","$72,000 a year","Écrire, modifier, intégrer et mettre à l'essai..."
26,CRC Tier 2 Data Analytics for Health Systems T...,University of Ottawa,"Ottawa, ON","$20,000 a year",How can applied AI and data analytics support ...
27,Analytics Client Lead and Development,Advanced Analytics and Research Lab (AAARL),"Toronto, ON•Remote","$3,500 a month","Attend analytics, data science, AI and industr..."
28,"Senior Director, Analytics and Insights",Bank of Canada,"Ottawa, ON","$166,000 - $207,000 a year","Lastly, you have experience leading analytics ..."
29,"Senior Institutional Analyst, Rankings, Analyt...",York University,"Toronto, ON","$92,622 a year",Minimum five years of demonstrated competencie...
30,Postdoctoral Fellow - Artificial Intelligence ...,University of Alberta,"Edmonton, AB","$45,000 a year",The position will be supported for one year wi...
31,Administrative Proceedings Specialist - Perfor...,CIUSSS de l'Ouest-de-l’Île-de-Montréal,"Verdun, QC",$23.63 - $43.63 an hour,"Développer, gérer ou conseiller sur des projet..."
32,Solution Architect - Analytics Environment,Bank of Canada,"Ottawa, ON","$95,482 - $119,352 a year",O using platforms and technologies related to ...
33,Account Delivery Manager Analytics,DXC Technology,"Toronto, ON•Remote","$89,000 - $134,400 a year",Who will be working as part of a global team t...
34,Professor in Business Analytics and AI (Predic...,University of Ottawa,"Ottawa, ON","$94,000 - $130,000 a year",The Telfer School of Management at the Univers...

In [72]:
yearly_salary = df.dropna()

In [73]:
yearly_salary.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 25 entries, 0 to 34
Data columns (total 5 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   job_title         25 non-null     object
 1   company_name      25 non-null     object
 2   company_location  25 non-null     object
 3   salary            25 non-null     object
 4   job_snippet       25 non-null     object
dtypes: object(5)
memory usage: 1.2+ KB

In [84]:
yearly_salary.reset_index(drop=True)

,job_title,company_name,company_location,salary,job_snippet
0,Data Scientist,Genpact,"Montréal, QC•Temporarily Remote","$55,590 - $118,000 a year",Knowledge of best practices in data analysis a...
1,Senior Machine Learning/ Data Scientist at Upw...,Upwork,Remote,"$100,000 - $200,000 a year","Collaborate closely with data scientists, engi..."
2,newData Scientist - Medical Diagnostics Projec...,CorGTA Inc.,"Ottawa, ON•Remote","$85,000 - $95,000 a year","Pay: $85,000 - $95,000 base plus benefits and ..."
3,data scientist,Tiger Analytics Inc.,"Toronto, ON•Remote","$110,000 - $130,000 a year","Research and document data requirements, data ..."
4,data scientist,BluVec Technologies INC,"Burnaby, BC","$70,000 - $120,000 a year","Research and document data requirements, data ..."
5,newData Scientist,Altair Engineering,"Toronto, ON","$59,394 - $141,315 a year",The goal of the data scientist is to provide i...
6,Data/Business Intelligence Analyst (Remote),Mero,"Toronto, ON•Remote","$30,000 - $65,000 a year",You will be closely involved with both the bus...
7,Database / Data Science Developer,AstraNorth,"Montréal, QC•Temporarily Remote","$54,434 a year",Data Science MS or Phd in Computer Science Dat...
8,Data Science Instructor,Juno College of Technology,"Toronto, ON•Remote","$70,000 - $85,000 a year",Are passionate about teaching data science and...
9,Data Scientist,Phyla,"Montréal, QC•Remote","$80,000 - $110,000 a year",Data science and AI: 3 years (required).\nExpe...
10,Join Statistics Canada for Assistant Director ...,Statistics Canada,"Ottawa, ON•Temporarily Remote","$122,991 - $140,571 a year",ASSET10 Experience in the implementation of so...
11,newartificial intelligence (AI) designer,MIR Services,"Concord, ON","$90,000 a year",Collect and document user's requirements and d...
12,Health Data Analyst,Sioux Lookout First Nations Health Authority,"Sioux Lookout, ON","$78,804 a year",Experience with common data science and data v...
13,"Data Analyst, Equity, Diversity and Inclusion",Waterloo Regional Police Service,"Cambridge, ON","$89,619 a year",Assist with data integrity and quality control...
14,BAND 2 - IT Data Analyst,BC Public Service,Canada,"$66,900 - $94,600 a year",Minimum 1 year of experience working on data a...
15,Canada / Stage Data Engineer/Scientist H/F,Neoxia,"Montréal, QC","$45,000 - $55,000 a year","Au sein de la Data Factory de Neoxia, tu pourr..."
16,"Senior Analyst, Advanced Analytics",Canadian Air Transport Security Authority,"Ottawa, ON","$68,475 - $85,649 a year",Graduation from a recognized university with a...
17,newprogrammeur/programmeuse en intelligence ar...,XEOS Imagerie inc.,"Quebec City, QC•Remote","$72,000 a year","Écrire, modifier, intégrer et mettre à l'essai..."
18,CRC Tier 2 Data Analytics for Health Systems T...,University of Ottawa,"Ottawa, ON","$20,000 a year",How can applied AI and data analytics support ...
19,"Senior Director, Analytics and Insights",Bank of Canada,"Ottawa, ON","$166,000 - $207,000 a year","Lastly, you have experience leading analytics ..."
20,"Senior Institutional Analyst, Rankings, Analyt...",York University,"Toronto, ON","$92,622 a year",Minimum five years of demonstrated competencie...
21,Postdoctoral Fellow - Artificial Intelligence ...,University of Alberta,"Edmonton, AB","$45,000 a year",The position will be supported for one year wi...
22,Solution Architect - Analytics Environment,Bank of Canada,"Ottawa, ON","$95,482 - $119,352 a year",O using platforms and technologies related to ...
23,Account Delivery Manager Analytics,DXC Technology,"Toronto, ON•Remote","$89,000 - $134,400 a year",Who will be working as part of a global team t...
24,Professor in Business Analytics and AI (Predic...,University of Ottawa,"Ottawa, ON","$94,000 - $130,000 a year",The Telfer School of Management at the Univers...

In [116]:
yearly_salary = yearly_salary[~yearly_salary.salary.str.contains("week","month")]

In [117]:
yearly_salary = yearly_salary[~yearly_salary.salary.str.contains("hour")]

In [119]:
yearly_salary = yearly_salary.reset_index(drop=True)

In [120]:
def strip_salary(x):
    nums = []
    y = x.replace('$','').replace(',','')
    for i in y.split():
        if i.isnumeric():
            nums.append(int(i))
    if len(nums) == 2:
        return 0.5*(nums[0]+nums[1])
    else:
        return nums[0]

In [123]:
yearly_salary['salary'] = yearly_salary.salary.map(strip_salary)

In [124]:
yearly_salary.head()

,job_title,company_name,company_location,salary,job_snippet
0,Data Scientist,Genpact,"Montréal, QC•Temporarily Remote",86795.0,Knowledge of best practices in data analysis a...
1,Senior Machine Learning/ Data Scientist at Upw...,Upwork,Remote,150000.0,"Collaborate closely with data scientists, engi..."
2,newData Scientist - Medical Diagnostics Projec...,CorGTA Inc.,"Ottawa, ON•Remote",90000.0,"Pay: $85,000 - $95,000 base plus benefits and ..."
3,data scientist,Tiger Analytics Inc.,"Toronto, ON•Remote",120000.0,"Research and document data requirements, data ..."
4,data scientist,BluVec Technologies INC,"Burnaby, BC",95000.0,"Research and document data requirements, data ..."

In [126]:
def convert_aud_to_gbp(amount):
    return amount*0.59

In [127]:
yearly_salary['salary'] = yearly_salary.salary.map(convert_aud_to_gbp)

In [130]:
ca_df = yearly_salary

In [132]:
ca_df['country_location'] = 'CA'

In [133]:
ca_df.to_csv('ca_df')

In [134]:
ca_df

,job_title,company_name,company_location,salary,job_snippet,country_location
0,Data Scientist,Genpact,"Montréal, QC•Temporarily Remote",51209.050,Knowledge of best practices in data analysis a...,CA
1,Senior Machine Learning/ Data Scientist at Upw...,Upwork,Remote,88500.000,"Collaborate closely with data scientists, engi...",CA
2,newData Scientist - Medical Diagnostics Projec...,CorGTA Inc.,"Ottawa, ON•Remote",53100.000,"Pay: $85,000 - $95,000 base plus benefits and ...",CA
3,data scientist,Tiger Analytics Inc.,"Toronto, ON•Remote",70800.000,"Research and document data requirements, data ...",CA
4,data scientist,BluVec Technologies INC,"Burnaby, BC",56050.000,"Research and document data requirements, data ...",CA
5,newData Scientist,Altair Engineering,"Toronto, ON",59209.155,The goal of the data scientist is to provide i...,CA
6,Data/Business Intelligence Analyst (Remote),Mero,"Toronto, ON•Remote",28025.000,You will be closely involved with both the bus...,CA
7,Database / Data Science Developer,AstraNorth,"Montréal, QC•Temporarily Remote",32116.060,Data Science MS or Phd in Computer Science Dat...,CA
8,Data Science Instructor,Juno College of Technology,"Toronto, ON•Remote",45725.000,Are passionate about teaching data science and...,CA
9,Data Scientist,Phyla,"Montréal, QC•Remote",56050.000,Data science and AI: 3 years (required).\nExpe...,CA
10,Join Statistics Canada for Assistant Director ...,Statistics Canada,"Ottawa, ON•Temporarily Remote",77750.790,ASSET10 Experience in the implementation of so...,CA
11,newartificial intelligence (AI) designer,MIR Services,"Concord, ON",53100.000,Collect and document user's requirements and d...,CA
12,Health Data Analyst,Sioux Lookout First Nations Health Authority,"Sioux Lookout, ON",46494.360,Experience with common data science and data v...,CA
13,"Data Analyst, Equity, Diversity and Inclusion",Waterloo Regional Police Service,"Cambridge, ON",52875.210,Assist with data integrity and quality control...,CA
14,BAND 2 - IT Data Analyst,BC Public Service,Canada,47642.500,Minimum 1 year of experience working on data a...,CA
15,Canada / Stage Data Engineer/Scientist H/F,Neoxia,"Montréal, QC",29500.000,"Au sein de la Data Factory de Neoxia, tu pourr...",CA
16,"Senior Analyst, Advanced Analytics",Canadian Air Transport Security Authority,"Ottawa, ON",45466.580,Graduation from a recognized university with a...,CA
17,newprogrammeur/programmeuse en intelligence ar...,XEOS Imagerie inc.,"Quebec City, QC•Remote",42480.000,"Écrire, modifier, intégrer et mettre à l'essai...",CA
18,CRC Tier 2 Data Analytics for Health Systems T...,University of Ottawa,"Ottawa, ON",11800.000,How can applied AI and data analytics support ...,CA
19,"Senior Director, Analytics and Insights",Bank of Canada,"Ottawa, ON",110035.000,"Lastly, you have experience leading analytics ...",CA
20,"Senior Institutional Analyst, Rankings, Analyt...",York University,"Toronto, ON",54646.980,Minimum five years of demonstrated competencie...,CA
21,Postdoctoral Fellow - Artificial Intelligence ...,University of Alberta,"Edmonton, AB",26550.000,The position will be supported for one year wi...,CA
22,Solution Architect - Analytics Environment,Bank of Canada,"Ottawa, ON",63376.030,O using platforms and technologies related to ...,CA
23,Account Delivery Manager Analytics,DXC Technology,"Toronto, ON•Remote",65903.000,Who will be working as part of a global team t...,CA
24,Professor in Business Analytics and AI (Predic...,University of Ottawa,"Ottawa, ON",66080.000,The Telfer School of Management at the Univers...,CA